export enum Status {
  NEW = 'NEW',
  CANCELLED = 'CANCELLED',
  PROCESSING = 'PROCESSING',
  PACKAGED = 'PACKAGED',
  PICKED = 'PICKED',
  SHIPPING = 'SHIPPING',
  DELIVERED = 'DELIVERED',
  REFUNDED = 'REFUNDED',
}
