name: CI/CD for main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create .env.production file
        run: |
          echo "VITE_SERVICE_ID=service_ibu5aw9" >> .env.production
          echo "VITE_TEMPLATE_ID=template_5dzxhxt" >> .env.production
          echo "VITE_PUBLIC_KEY=FjAV1de0oEJKhJymj" >> .env.production
          echo "VITE_BACKEND_URL=https://haquocbao.id.vn:8080/api/v1/" >> .env.production
          echo "VITE_HUGGINGFACE_API_KEY=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" >> .env.production

      - name: Build project
        run: npm run build

      - name: Create 404.html for SPA fallback
        run: |
          cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
