name: CI

on:
  push:
    branches: [template-3]
  pull_request:
    branches: [template-3]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck || echo "No typecheck script found"

      - name: Test with coverage
        run: npm run test:coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Build
        run: npm run build

      - name: Show coverage summary
        if: always()
        run: |
          if [ -f coverage/lcov-report/index.html ]; then
            echo "Coverage HTML report generated at coverage/lcov-report/index.html"
          fi